### ISSUE TITLE
Issue with TagBamWithReadSequenceExtended, NativeLibraryLoader, unable to load file

### ISSUE THREAD

**Issue by SayanNanda** [broadinstitute/Drop-seq#120]
Hi,
I'm trying to run the bash file using the command,
bash Drop-seq_alignment.sh -g /home/alpha/gene_alignment_star/genome_index/ -r /home/alpha/Drop-seq_tools-2.1.0/fromLocal/GSM1629193_hg19_ERCC.fasta -t ./tmpDir ./fromLocal/GSM1629193_ERCC.bam

The files I'm using are the same as that of the human genome example. The Star genome index was created using STAR's generate genome and was successfully used to align a fasta file.
I tried searching for a solution to a problem and it appears there was a similar issue previously however that got solved by including a temporary directory, hence I added the same in the command line.
This is the stdout from the execution.
********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    TagBamWithReadSequenceExtended -SUMMARY /home/alpha/Drop-seq_tools-2.1.0/unaligned_tagged_Cellular.bam_summary.txt -BASE_RANGE 1-12 -BASE_QUALITY 10 -BARCODED_READ 1 -DISCARD_READ false -TAG_NAME XC -NUM_BASES_BELOW_QUALITY 1 -INPUT ./fromLocal/GSM1629193_ERCC.bam -OUTPUT ./tmpDir/unaligned_tagged_Cell.bam
**********

10:59:14.203 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/home/alpha/Drop-seq_tools-2.1.0/jar/lib/picard-2.18.14.jar!/com/intel/gkl/native/libgkl_compression.so
10:59:14.220 WARN  NativeLibraryLoader - Unable to load libgkl_compression.so from native/libgkl_compression.so (No such file or directory)
10:59:14.221 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/home/alpha/Drop-seq_tools-2.1.0/jar/lib/picard-2.18.14.jar!/com/intel/gkl/native/libgkl_compression.so
10:59:14.221 WARN  NativeLibraryLoader - Unable to load libgkl_compression.so from native/libgkl_compression.so (No such file or directory)
[Tue Apr 16 10:59:14 PDT 2019] TagBamWithReadSequenceExtended INPUT=./fromLocal/GSM1629193_ERCC.bam OUTPUT=./tmpDir/unaligned_tagged_Cell.bam SUMMARY=/home/alpha/Drop-seq_tools-2.1.0/unaligned_tagged_Cellular.bam_summary.txt BASE_RANGE=1-12 BARCODED_READ=1 DISCARD_READ=false BASE_QUALITY=10 NUM_BASES_BELOW_QUALITY=1 TAG_NAME=XC    TAG_BARCODED_READ=false HARD_CLIP_BASES=false TAG_QUALITY=XQ VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Tue Apr 16 10:59:14 PDT 2019] Executing as alpha@hida on Linux 4.4.0-143-generic amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_211-b12; Deflater: Jdk; Inflater: Jdk; Provider GCS is not available; Picard version: 2.1.0(e9a342e_1547567906)
10:59:14.249 WARN  IntelDeflaterFactory - IntelInflater is not supported, using Java.util.zip.Inflater
INFO    2019-04-16 10:59:14     CustomBAMIterators      Input SAM/BAM not in queryname order, sorting...
INFO    2019-04-16 10:59:14     CustomBAMIterators      Reading in records for query name sorting
[Tue Apr 16 10:59:26 PDT 2019] org.broadinstitute.dropseqrna.utils.TagBamWithReadSequenceExtended done. Elapsed time: 0.20 minutes.
Runtime.totalMemory()=2216165376
Exception in thread "main" htsjdk.samtools.util.RuntimeIOException: java.nio.file.NoSuchFileException: /alpha/sortingcollection.3061711125641775730.tmp
        at htsjdk.samtools.util.SortingCollection.spillToDisk(SortingCollection.java:268)
        at htsjdk.samtools.util.SortingCollection.add(SortingCollection.java:183)
        at org.broadinstitute.dropseqrna.utils.SortingIteratorFactory.create(SortingIteratorFactory.java:67)
        at org.broadinstitute.dropseqrna.utils.readiterators.SamRecordSortingIteratorFactory.create(SamRecordSortingIteratorFactory.java:57)
        at org.broadinstitute.dropseqrna.utils.CustomBAMIterators.getQuerynameSortedRecords(CustomBAMIterators.java:84)
        at org.broadinstitute.dropseqrna.utils.TagBamWithReadSequenceExtended.doWork(TagBamWithReadSequenceExtended.java:103)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:295)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
        at org.broadinstitute.dropseqrna.cmdline.DropSeqMain.main(DropSeqMain.java:42)
Caused by: java.nio.file.NoSuchFileException: /alpha/sortingcollection.3061711125641775730.tmp
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.createFile(Files.java:632)
        at java.nio.file.TempFileHelper.create(TempFileHelper.java:138)
        at java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:161)
        at java.nio.file.Files.createTempFile(Files.java:852)
        at htsjdk.samtools.util.IOUtil.newTempPath(IOUtil.java:328)
        at htsjdk.samtools.util.SortingCollection.newTempFile(SortingCollection.java:279)
        at htsjdk.samtools.util.SortingCollection.spillToDisk(SortingCollection.java:250)
        ... 8 more

I am using the drop seq version 2.1.0. This is my first time using the tool and I haven't used Picard before so I'm not sure of what I'm doing wrong, any help would be greatly appreciated.
Thank you,
Sayan

**Comment by alecw** [comment]
Hi @SayanNanda ,

Your TMPDIR environment variable refers to a directory that does not exist.  Try something like this before invoking the script:

`export TMPDIR=/tmp`

Replace /tmp with whatever would be appropriate for your system.

**Comment by SayanNanda** [comment]
Thank you, this solved the problem!

**Comment by Yichel518** [comment]
Hello,  @SayanNanda I met the same problem as you, but I do not how to set correct tmpdir to debug, can you help me? Thank you!

**Comment by alecw** [comment]
Hi @Yichel518 ,

Did you try what I suggested to SayanNanda?

-Alec

**Comment by Yichel518** [comment]
> Hi @Yichel518 ,
> 
> Did you try what I suggested to SayanNanda?
>
> -Alec



> Hi @Yichel518 ,
> 
> Did you try what I suggested to SayanNanda?
> 
> -Alec
Hi, Alec 
Thank you for your reply!
my problem is run Drop-seq_tools-2.3.0/TagBamWithReadSequenceExtended INPUT=/home/yxtu/result/ubam/3-somite_Rep_1.ubam OUTPUT=/home/yxtu/result/taggedbam/3-somite_Rep_1_unaligned_tagged_Cell.bam SUMMARY=/home/yxtu/result/taggedbam/3-somite_Rep_1_unaligned_tagged_Cell.bam_summary.txt BASE_RANGE=1-12 BASE_QUALITY=10 BARCODED_READ=1 DISCARD_READ=False TAG_NAME=XC NUM_BASES_BELOW_QUALITY=1
but there is a error:
![image](https://user-images.githubusercontent.com/52185244/60515623-9bc51c00-9d0e-11e9-9a2f-ca00b487d7da.png)
Alec, what should I do?
thangk you!

**Comment by alecw** [comment]
Hi @SayanNanda ,

The issue on which you are commenting is not related to your problem, other than it was an issue with the same program.  You should create a new issue if you want help with your problem.  However, the error message is clear.  You are trying to extract bases 1-12 from your input, but apparently at least some of your reads are only 10 bases long.  You need to look at what produced your input BAM to understand why your reads are so short.

If you want to continue this conversation, please create a new issue.

-Alec
