### ISSUE TITLE
DigitalExpression Exception in thread "main" htsjdk.samtools.util.RuntimeIOException

### ISSUE THREAD

**Issue by MartaBenegas** [broadinstitute/Drop-seq#187]
Hi, I'm trying to run DigitalExpression step but I get the following error, which I don't understand.
I've made all previous steps (exept detect bead substituton and synthesis errors) and they worked fine. I'm working on an AWS with linux (Linux 4.14.173-137.229.amzn2.x86_64). 

```
[ec2-user@ip-172-31-16-254 dropseq_test]$ /mnt/disk/utils/Drop-seq_tools-2.3.0/DigitalExpression O=dge_heart10x_dropseq.txt OUTPUT_LONG_FORMAT=dge_long.txt I=/mnt/disk/dropseq_test/gene_exon_tagged.bam MIN_NUM_GENES_PER_CELL=500 RARE_UMI_FILTER_THRESHOLD=0.01 STRAND_STRATEGY=BOTH SUMMARY=summary_dge_heart10x_dropseq.txt
INFO    2020-04-26 15:34:32     DigitalExpression

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    DigitalExpression -O dge_heart10x_dropseq.txt -OUTPUT_LONG_FORMAT dge_long.txt -I /mnt/disk/dropseq_test/gene_exon_tagged.bam -MIN_NUM_GENES_PER_CELL 500 -RARE_UMI_FILTER_THRESHOLD 0.01 -STR
AND_STRATEGY BOTH -SUMMARY summary_dge_heart10x_dropseq.txt
**********


15:34:32.562 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/mnt/disk/utils/Drop-seq_tools-2.3.0/jar/lib/picard-2.18.14.jar!/com/intel/gkl/native/libgkl_compression.so
15:34:32.570 WARN  NativeLibraryLoader - Unable to load libgkl_compression.so from native/libgkl_compression.so (No such file or directory)
15:34:32.571 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/mnt/disk/utils/Drop-seq_tools-2.3.0/jar/lib/picard-2.18.14.jar!/com/intel/gkl/native/libgkl_compression.so
15:34:32.571 WARN  NativeLibraryLoader - Unable to load libgkl_compression.so from native/libgkl_compression.so (No such file or directory)
[Sun Apr 26 15:34:32 UTC 2020] DigitalExpression SUMMARY=summary_dge_heart10x_dropseq.txt OUTPUT=dge_heart10x_dropseq.txt OUTPUT_LONG_FORMAT=dge_long.txt INPUT=/mnt/disk/dropseq_test/gene_exon_tagged.bam MIN_NUM_GENES_PER_CELL=500 RARE_UMI_FILTER_THRESHOLD=0.01 STRAND_STRATEGY=BOTH    OUTPUT_READS_INSTEAD=false CELL_BARCODE_TAG=XC MOLECULAR_BARCODE_TAG=XM EDIT_DISTANCE=1 READ_MQ=10 MIN_BC_READ_THRESHOLD=0 USE_STRAND_INFO=true GENE_NAME_TAG=gn GENE_STRAND_TAG=gs GENE_FUNCTION_TAG=gf LOCUS_FUNCTION_LIST=[CODING, UTR] VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Sun Apr 26 15:34:32 UTC 2020] Executing as ec2-user@ip-172-31-16-254.us-east-2.compute.internal on Linux 4.14.173-137.229.amzn2.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_242-b08; Deflater: Jdk; Inflater: Jdk; Provider GCS is not available; Picard version: 2.3.0(34e6572_1555443285)
INFO    2020-04-26 15:34:32     BarcodeListRetrieval    Looking for cell barcodes that have at least 500 genes
15:34:32.583 WARN  IntelDeflaterFactory - IntelInflater is not supported, using Java.util.zip.Inflater
INFO    2020-04-26 15:34:32     CustomBAMIterators      Reading in records for TAG name sorting
[Sun Apr 26 15:34:39 UTC 2020] org.broadinstitute.dropseqrna.barnyard.DigitalExpression done. Elapsed time: 0,12 minutes.
Runtime.totalMemory()=1585971200
Exception in thread "main" htsjdk.samtools.util.RuntimeIOException: java.nio.file.NoSuchFileException: /ec2-user/sortingcollection.2824934265661879508.tmp
        at htsjdk.samtools.util.SortingCollection.spillToDisk(SortingCollection.java:268)
        at htsjdk.samtools.util.SortingCollection.add(SortingCollection.java:183)
        at org.broadinstitute.dropseqrna.utils.SortingIteratorFactory.create(SortingIteratorFactory.java:67)
        at org.broadinstitute.dropseqrna.utils.readiterators.SamRecordSortingIteratorFactory.create(SamRecordSortingIteratorFactory.java:57)
        at org.broadinstitute.dropseqrna.utils.CustomBAMIterators.getReadsInTagOrder(CustomBAMIterators.java:54)
        at org.broadinstitute.dropseqrna.metrics.BamTagOfTagCounts.getResults(BamTagOfTagCounts.java:109)
        at org.broadinstitute.dropseqrna.barnyard.BarcodeListRetrieval.getListCellBarcodesByGeneCount(BarcodeListRetrieval.java:139)
        at org.broadinstitute.dropseqrna.barnyard.BarcodeListRetrieval.getCellBarcodes(BarcodeListRetrieval.java:73)
        at org.broadinstitute.dropseqrna.barnyard.DigitalExpression.doWork(DigitalExpression.java:144)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:295)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
        at org.broadinstitute.dropseqrna.cmdline.DropSeqMain.main(DropSeqMain.java:42)
Caused by: java.nio.file.NoSuchFileException: /ec2-user/sortingcollection.2824934265661879508.tmp
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.createFile(Files.java:632)
        at java.nio.file.TempFileHelper.create(TempFileHelper.java:138)
        at java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:161)
        at java.nio.file.Files.createTempFile(Files.java:852)
        at htsjdk.samtools.util.IOUtil.newTempPath(IOUtil.java:328)
        at htsjdk.samtools.util.SortingCollection.newTempFile(SortingCollection.java:279)
        at htsjdk.samtools.util.SortingCollection.spillToDisk(SortingCollection.java:250)
        ... 11 more
```
Thanks in advance for your help. I've really liked your software so far!

**Comment by jamesnemesh** [comment]
The program is saying that it can’t find the temp files it wants to read/write.

Looks like you’re running on amazon cloud, which may make this more complicated.  You might try to explicitly define where the temp files should go via the TMP_DIR option.

-Jim

**Comment by MartaBenegas** [comment]
It worked! Thank you Jim. But now it seems that it does not produce or does not save any output:

```
[ec2-user@ip-172-31-16-254 dropseq_test]$ /mnt/disk/utils/Drop-seq_tools-2.3.0/DigitalExpression O=dge_heart10x_dropseq.txt OUTPUT_LONG_FORMAT=dge_long.txt I=/mnt/disk/dropseq_test/gene_exon_tagged.bam MI
N_NUM_GENES_PER_CELL=500 RARE_UMI_FILTER_THRESHOLD=0.01 STRAND_STRATEGY=BOTH SUMMARY=summary_dge_heart10x_dropseq.txt TMP_DIR=/tmp
INFO    2020-04-26 18:19:44     DigitalExpression

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    DigitalExpression -O dge_heart10x_dropseq.txt -OUTPUT_LONG_FORMAT dge_long.txt -I /mnt/disk/dropseq_test/gene_exon_tagged.bam -MIN_NUM_GENES_PER_CELL 500 -RARE_UMI_FILTER_THRESHOLD 0.01 -STR
AND_STRATEGY BOTH -SUMMARY summary_dge_heart10x_dropseq.txt -TMP_DIR /tmp
**********


18:19:44.383 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/mnt/disk/utils/Drop-seq_tools-2.3.0/jar/lib/picard-2.18.14.jar!/com/intel/gkl/native/libgkl_compression.so
[Sun Apr 26 18:19:44 UTC 2020] DigitalExpression SUMMARY=summary_dge_heart10x_dropseq.txt OUTPUT=dge_heart10x_dropseq.txt OUTPUT_LONG_FORMAT=dge_long.txt INPUT=/mnt/disk/dropseq_test/gene_exon_tagged.bam 
MIN_NUM_GENES_PER_CELL=500 RARE_UMI_FILTER_THRESHOLD=0.01 STRAND_STRATEGY=BOTH TMP_DIR=[/tmp]    OUTPUT_READS_INSTEAD=false CELL_BARCODE_TAG=XC MOLECULAR_BARCODE_TAG=XM EDIT_DISTANCE=1 READ_MQ=10 MIN_BC_R
EAD_THRESHOLD=0 USE_STRAND_INFO=true GENE_NAME_TAG=gn GENE_STRAND_TAG=gs GENE_FUNCTION_TAG=gf LOCUS_FUNCTION_LIST=[CODING, UTR] VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 
MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Sun Apr 26 18:19:44 UTC 2020] Executing as ec2-user@ip-172-31-16-254.us-east-2.compute.internal on Linux 4.14.173-137.229.amzn2.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_242-b08; Deflater: Intel; Infl
ater: Intel; Provider GCS is not available; Picard version: 2.3.0(34e6572_1555443285)
INFO    2020-04-26 18:19:44     BarcodeListRetrieval    Looking for cell barcodes that have at least 500 genes
INFO    2020-04-26 18:19:44     CustomBAMIterators      Reading in records for TAG name sorting
INFO    2020-04-26 18:19:55     CustomBAMIterators      Processed     1.000.000 records.  Elapsed time: 00:00:10s.  Time for last 1.000.000:   10s.  Last read position: 1:24.615.107
INFO    2020-04-26 18:20:03     CustomBAMIterators      Processed     2.000.000 records.  Elapsed time: 00:00:19s.  Time for last 1.000.000:    8s.  Last read position: 1:87.227.826
INFO    2020-04-26 18:20:11     CustomBAMIterators      Processed     3.000.000 records.  Elapsed time: 00:00:26s.  Time for last 1.000.000:    7s.  Last read position: 2:10.059.000
INFO    2020-04-26 18:20:18     CustomBAMIterators      Processed     4.000.000 records.  Elapsed time: 00:00:34s.  Time for last 1.000.000:    7s.  Last read position: 2:91.929.903
INFO    2020-04-26 18:20:23     CustomBAMIterators      Processed     5.000.000 records.  Elapsed time: 00:00:39s.  Time for last 1.000.000:    4s.  Last read position: 2:177.460.459
INFO    2020-04-26 18:20:31     CustomBAMIterators      Processed     6.000.000 records.  Elapsed time: 00:00:47s.  Time for last 1.000.000:    7s.  Last read position: 3:95.945.458
INFO    2020-04-26 18:20:36     CustomBAMIterators      Processed     7.000.000 records.  Elapsed time: 00:00:51s.  Time for last 1.000.000:    4s.  Last read position: 4:43.514.759
INFO    2020-04-26 18:20:40     CustomBAMIterators      Processed     8.000.000 records.  Elapsed time: 00:00:56s.  Time for last 1.000.000:    4s.  Last read position: 4:131.948.849
INFO    2020-04-26 18:20:48     CustomBAMIterators      Processed     9.000.000 records.  Elapsed time: 00:01:04s.  Time for last 1.000.000:    7s.  Last read position: 5:34.654.501
INFO    2020-04-26 18:20:53     CustomBAMIterators      Processed    10.000.000 records.  Elapsed time: 00:01:08s.  Time for last 1.000.000:    4s.  Last read position: 5:122.456.402
INFO    2020-04-26 18:20:57     CustomBAMIterators      Processed    11.000.000 records.  Elapsed time: 00:01:13s.  Time for last 1.000.000:    4s.  Last read position: 6:28.424.200
INFO    2020-04-26 18:21:04     CustomBAMIterators      Processed    12.000.000 records.  Elapsed time: 00:01:20s.  Time for last 1.000.000:    7s.  Last read position: 6:113.324.517
INFO    2020-04-26 18:21:09     CustomBAMIterators      Processed    13.000.000 records.  Elapsed time: 00:01:24s.  Time for last 1.000.000:    4s.  Last read position: 7:12.925.780
INFO    2020-04-26 18:21:13     CustomBAMIterators      Processed    14.000.000 records.  Elapsed time: 00:01:28s.  Time for last 1.000.000:    4s.  Last read position: 7:45.126.000
INFO    2020-04-26 18:21:17     CustomBAMIterators      Processed    15.000.000 records.  Elapsed time: 00:01:32s.  Time for last 1.000.000:    3s.  Last read position: 7:103.812.601
INFO    2020-04-26 18:21:21     CustomBAMIterators      Processed    16.000.000 records.  Elapsed time: 00:01:36s.  Time for last 1.000.000:    3s.  Last read position: 7:103.826.640
INFO    2020-04-26 18:21:31     CustomBAMIterators      Processed    17.000.000 records.  Elapsed time: 00:01:46s.  Time for last 1.000.000:    9s.  Last read position: 7:103.826.722
INFO    2020-04-26 18:21:36     CustomBAMIterators      Processed    18.000.000 records.  Elapsed time: 00:01:51s.  Time for last 1.000.000:    5s.  Last read position: 7:137.468.018
INFO    2020-04-26 18:21:44     CustomBAMIterators      Processed    19.000.000 records.  Elapsed time: 00:02:00s.  Time for last 1.000.000:    8s.  Last read position: 8:72.566.077
INFO    2020-04-26 18:21:49     CustomBAMIterators      Processed    20.000.000 records.  Elapsed time: 00:02:04s.  Time for last 1.000.000:    4s.  Last read position: 9:21.387.762
INFO    2020-04-26 18:21:54     CustomBAMIterators      Processed    21.000.000 records.  Elapsed time: 00:02:09s.  Time for last 1.000.000:    4s.  Last read position: 9:66.949.332
INFO    2020-04-26 18:22:01     CustomBAMIterators      Processed    22.000.000 records.  Elapsed time: 00:02:17s.  Time for last 1.000.000:    7s.  Last read position: 9:120.573.815
INFO    2020-04-26 18:22:06     CustomBAMIterators      Processed    23.000.000 records.  Elapsed time: 00:02:22s.  Time for last 1.000.000:    4s.  Last read position: 10:80.293.803
INFO    2020-04-26 18:22:11     CustomBAMIterators      Processed    24.000.000 records.  Elapsed time: 00:02:26s.  Time for last 1.000.000:    4s.  Last read position: 11:5.818.448
INFO    2020-04-26 18:22:15     CustomBAMIterators      Processed    25.000.000 records.  Elapsed time: 00:02:31s.  Time for last 1.000.000:    4s.  Last read position: 11:32.284.261
INFO    2020-04-26 18:22:19     CustomBAMIterators      Processed    26.000.000 records.  Elapsed time: 00:02:35s.  Time for last 1.000.000:    3s.  Last read position: 11:32.297.123
INFO    2020-04-26 18:22:23     CustomBAMIterators      Processed    27.000.000 records.  Elapsed time: 00:02:39s.  Time for last 1.000.000:    3s.  Last read position: 11:62.552.994
INFO    2020-04-26 18:22:27     CustomBAMIterators      Processed    28.000.000 records.  Elapsed time: 00:02:42s.  Time for last 1.000.000:    3s.  Last read position: 11:96.248.996
INFO    2020-04-26 18:22:31     CustomBAMIterators      Processed    29.000.000 records.  Elapsed time: 00:02:46s.  Time for last 1.000.000:    3s.  Last read position: 11:120.605.489
INFO    2020-04-26 18:22:35     CustomBAMIterators      Processed    30.000.000 records.  Elapsed time: 00:02:50s.  Time for last 1.000.000:    3s.  Last read position: 12:109.894.421
INFO    2020-04-26 18:22:39     CustomBAMIterators      Processed    31.000.000 records.  Elapsed time: 00:02:54s.  Time for last 1.000.000:    3s.  Last read position: 13:60.174.538
INFO    2020-04-26 18:22:43     CustomBAMIterators      Processed    32.000.000 records.  Elapsed time: 00:02:58s.  Time for last 1.000.000:    4s.  Last read position: 14:52.903.038
INFO    2020-04-26 18:22:47     CustomBAMIterators      Processed    33.000.000 records.  Elapsed time: 00:03:02s.  Time for last 1.000.000:    4s.  Last read position: 15:37.943.442
INFO    2020-04-26 18:22:51     CustomBAMIterators      Processed    34.000.000 records.  Elapsed time: 00:03:06s.  Time for last 1.000.000:    3s.  Last read position: 15:98.999.437
INFO    2020-04-26 18:23:01     CustomBAMIterators      Processed    35.000.000 records.  Elapsed time: 00:03:16s.  Time for last 1.000.000:    9s.  Last read position: 17:3.043.996
INFO    2020-04-26 18:23:11     CustomBAMIterators      Processed    36.000.000 records.  Elapsed time: 00:03:26s.  Time for last 1.000.000:   10s.  Last read position: 17:34.095.006
INFO    2020-04-26 18:23:16     CustomBAMIterators      Processed    37.000.000 records.  Elapsed time: 00:03:32s.  Time for last 1.000.000:    5s.  Last read position: 18:10.627.814
INFO    2020-04-26 18:23:26     CustomBAMIterators      Processed    38.000.000 records.  Elapsed time: 00:03:41s.  Time for last 1.000.000:    9s.  Last read position: 19:5.383.669
INFO    2020-04-26 18:23:31     CustomBAMIterators      Processed    39.000.000 records.  Elapsed time: 00:03:46s.  Time for last 1.000.000:    5s.  Last read position: 19:29.384.703
INFO    2020-04-26 18:23:40     CustomBAMIterators      Processed    40.000.000 records.  Elapsed time: 00:03:56s.  Time for last 1.000.000:    9s.  Last read position: X:104.345.359
INFO    2020-04-26 18:23:45     CustomBAMIterators      Processed    41.000.000 records.  Elapsed time: 00:04:01s.  Time for last 1.000.000:    5s.  Last read position: CHR_MG3700_PATCH:77.774.500
INFO    2020-04-26 18:23:49     CustomBAMIterators      Processed    42.000.000 records.  Elapsed time: 00:04:04s.  Time for last 1.000.000:    3s.  Last read position: */*
INFO    2020-04-26 18:23:52     CustomBAMIterators      Processed    43.000.000 records.  Elapsed time: 00:04:07s.  Time for last 1.000.000:    3s.  Last read position: */*
INFO    2020-04-26 18:23:55     CustomBAMIterators      Processed    44.000.000 records.  Elapsed time: 00:04:10s.  Time for last 1.000.000:    3s.  Last read position: */*
INFO    2020-04-26 18:23:56     SortingCollection       Creating merging iterator from 89 files
INFO    2020-04-26 18:23:57     CustomBAMIterators      Sorting finished.
INFO    2020-04-26 18:23:58     BamTagOfTagCounts       Processed     1.000.000 records.  Elapsed time: 00:00:01s.  Time for last 1.000.000:    1s.  Last read position: 1:24.615.107
INFO    2020-04-26 18:23:59     BamTagOfTagCounts       Processed     2.000.000 records.  Elapsed time: 00:00:02s.  Time for last 1.000.000:    1s.  Last read position: 1:87.227.826
INFO    2020-04-26 18:24:00     BamTagOfTagCounts       Processed     3.000.000 records.  Elapsed time: 00:00:03s.  Time for last 1.000.000:    1s.  Last read position: 2:10.059.000
INFO    2020-04-26 18:24:01     BamTagOfTagCounts       Processed     4.000.000 records.  Elapsed time: 00:00:04s.  Time for last 1.000.000:    1s.  Last read position: 2:91.929.903
INFO    2020-04-26 18:24:02     BamTagOfTagCounts       Processed     5.000.000 records.  Elapsed time: 00:00:05s.  Time for last 1.000.000:    1s.  Last read position: 2:177.460.459
INFO    2020-04-26 18:24:04     BamTagOfTagCounts       Processed     6.000.000 records.  Elapsed time: 00:00:07s.  Time for last 1.000.000:    1s.  Last read position: 3:95.945.458
INFO    2020-04-26 18:24:05     BamTagOfTagCounts       Processed     7.000.000 records.  Elapsed time: 00:00:08s.  Time for last 1.000.000:    1s.  Last read position: 4:43.514.759
INFO    2020-04-26 18:24:06     BamTagOfTagCounts       Processed     8.000.000 records.  Elapsed time: 00:00:09s.  Time for last 1.000.000:    1s.  Last read position: 4:131.948.849
INFO    2020-04-26 18:24:07     BamTagOfTagCounts       Processed     9.000.000 records.  Elapsed time: 00:00:10s.  Time for last 1.000.000:    1s.  Last read position: 5:34.654.501
INFO    2020-04-26 18:24:08     BamTagOfTagCounts       Processed    10.000.000 records.  Elapsed time: 00:00:11s.  Time for last 1.000.000:    1s.  Last read position: 5:122.456.402
INFO    2020-04-26 18:24:10     BamTagOfTagCounts       Processed    11.000.000 records.  Elapsed time: 00:00:12s.  Time for last 1.000.000:    1s.  Last read position: 6:28.424.200
INFO    2020-04-26 18:24:11     BamTagOfTagCounts       Processed    12.000.000 records.  Elapsed time: 00:00:14s.  Time for last 1.000.000:    1s.  Last read position: 6:113.324.517
INFO    2020-04-26 18:24:12     BamTagOfTagCounts       Processed    13.000.000 records.  Elapsed time: 00:00:15s.  Time for last 1.000.000:    1s.  Last read position: 7:12.925.780
INFO    2020-04-26 18:24:13     BamTagOfTagCounts       Processed    14.000.000 records.  Elapsed time: 00:00:16s.  Time for last 1.000.000:    1s.  Last read position: 7:45.126.000
INFO    2020-04-26 18:24:14     BamTagOfTagCounts       Processed    15.000.000 records.  Elapsed time: 00:00:17s.  Time for last 1.000.000:    1s.  Last read position: 7:103.812.601
INFO    2020-04-26 18:24:15     BamTagOfTagCounts       Processed    16.000.000 records.  Elapsed time: 00:00:18s.  Time for last 1.000.000:    1s.  Last read position: 7:103.826.640
INFO    2020-04-26 18:24:17     BamTagOfTagCounts       Processed    17.000.000 records.  Elapsed time: 00:00:19s.  Time for last 1.000.000:    1s.  Last read position: 7:103.826.722
INFO    2020-04-26 18:24:18     BamTagOfTagCounts       Processed    18.000.000 records.  Elapsed time: 00:00:21s.  Time for last 1.000.000:    1s.  Last read position: 7:137.468.018
INFO    2020-04-26 18:24:19     BamTagOfTagCounts       Processed    19.000.000 records.  Elapsed time: 00:00:22s.  Time for last 1.000.000:    1s.  Last read position: 8:72.566.077
INFO    2020-04-26 18:24:20     BamTagOfTagCounts       Processed    20.000.000 records.  Elapsed time: 00:00:23s.  Time for last 1.000.000:    1s.  Last read position: 9:21.387.762
INFO    2020-04-26 18:24:21     BamTagOfTagCounts       Processed    21.000.000 records.  Elapsed time: 00:00:24s.  Time for last 1.000.000:    1s.  Last read position: 9:66.949.332
INFO    2020-04-26 18:24:22     BamTagOfTagCounts       Processed    22.000.000 records.  Elapsed time: 00:00:25s.  Time for last 1.000.000:    1s.  Last read position: 9:120.573.815
INFO    2020-04-26 18:24:24     BamTagOfTagCounts       Processed    23.000.000 records.  Elapsed time: 00:00:27s.  Time for last 1.000.000:    1s.  Last read position: 10:80.293.803
INFO    2020-04-26 18:24:25     BamTagOfTagCounts       Processed    24.000.000 records.  Elapsed time: 00:00:28s.  Time for last 1.000.000:    1s.  Last read position: 11:5.818.448
INFO    2020-04-26 18:24:26     BamTagOfTagCounts       Processed    25.000.000 records.  Elapsed time: 00:00:29s.  Time for last 1.000.000:    1s.  Last read position: 11:32.284.261
INFO    2020-04-26 18:24:27     BamTagOfTagCounts       Processed    26.000.000 records.  Elapsed time: 00:00:30s.  Time for last 1.000.000:    1s.  Last read position: 11:32.297.123
INFO    2020-04-26 18:24:28     BamTagOfTagCounts       Processed    27.000.000 records.  Elapsed time: 00:00:31s.  Time for last 1.000.000:    1s.  Last read position: 11:62.552.994
INFO    2020-04-26 18:24:29     BamTagOfTagCounts       Processed    28.000.000 records.  Elapsed time: 00:00:32s.  Time for last 1.000.000:    1s.  Last read position: 11:96.248.996
INFO    2020-04-26 18:24:30     BamTagOfTagCounts       Processed    29.000.000 records.  Elapsed time: 00:00:33s.  Time for last 1.000.000:    1s.  Last read position: 11:120.605.489
INFO    2020-04-26 18:24:32     BamTagOfTagCounts       Processed    30.000.000 records.  Elapsed time: 00:00:35s.  Time for last 1.000.000:    1s.  Last read position: 12:109.894.421
INFO    2020-04-26 18:24:33     BamTagOfTagCounts       Processed    31.000.000 records.  Elapsed time: 00:00:36s.  Time for last 1.000.000:    1s.  Last read position: 13:60.174.538
INFO    2020-04-26 18:24:34     BamTagOfTagCounts       Processed    32.000.000 records.  Elapsed time: 00:00:37s.  Time for last 1.000.000:    1s.  Last read position: 14:52.903.038
INFO    2020-04-26 18:24:35     BamTagOfTagCounts       Processed    33.000.000 records.  Elapsed time: 00:00:38s.  Time for last 1.000.000:    1s.  Last read position: 15:37.943.442
INFO    2020-04-26 18:24:36     BamTagOfTagCounts       Processed    34.000.000 records.  Elapsed time: 00:00:39s.  Time for last 1.000.000:    1s.  Last read position: 15:98.999.437
INFO    2020-04-26 18:24:37     BamTagOfTagCounts       Processed    35.000.000 records.  Elapsed time: 00:00:40s.  Time for last 1.000.000:    1s.  Last read position: 17:3.043.996
INFO    2020-04-26 18:24:39     BamTagOfTagCounts       Processed    36.000.000 records.  Elapsed time: 00:00:41s.  Time for last 1.000.000:    1s.  Last read position: 17:34.095.006
INFO    2020-04-26 18:24:40     BamTagOfTagCounts       Processed    37.000.000 records.  Elapsed time: 00:00:43s.  Time for last 1.000.000:    1s.  Last read position: 18:10.627.814
INFO    2020-04-26 18:24:41     BamTagOfTagCounts       Processed    38.000.000 records.  Elapsed time: 00:00:44s.  Time for last 1.000.000:    1s.  Last read position: 19:5.383.669
INFO    2020-04-26 18:24:42     BamTagOfTagCounts       Processed    39.000.000 records.  Elapsed time: 00:00:45s.  Time for last 1.000.000:    1s.  Last read position: 19:29.384.703
INFO    2020-04-26 18:24:43     BamTagOfTagCounts       Processed    40.000.000 records.  Elapsed time: 00:00:46s.  Time for last 1.000.000:    1s.  Last read position: X:104.345.359
INFO    2020-04-26 18:24:44     BamTagOfTagCounts       Processed    41.000.000 records.  Elapsed time: 00:00:47s.  Time for last 1.000.000:    1s.  Last read position: CHR_MG3700_PATCH:77.774.500
INFO    2020-04-26 18:24:45     BamTagOfTagCounts       Processed    42.000.000 records.  Elapsed time: 00:00:48s.  Time for last 1.000.000:    0s.  Last read position: */*
INFO    2020-04-26 18:24:46     BamTagOfTagCounts       Processed    43.000.000 records.  Elapsed time: 00:00:49s.  Time for last 1.000.000:    0s.  Last read position: */*
INFO    2020-04-26 18:24:47     BamTagOfTagCounts       Processed    44.000.000 records.  Elapsed time: 00:00:50s.  Time for last 1.000.000:    0s.  Last read position: */*
ERROR   2020-04-26 18:24:47     DigitalExpression       Running digital expression without somehow selecting a set of barcodes to process no longer supported.
[Sun Apr 26 18:24:47 UTC 2020] org.broadinstitute.dropseqrna.barnyard.DigitalExpression done. Elapsed time: 5,06 minutes.
Runtime.totalMemory()=3404201984
```
And there is not any dge_heart10x_dropseq.txt nor dge_long.txt :
```
[ec2-user@ip-172-31-16-254 dropseq_test]$ ll
total 18470376
lrwxrwxrwx 1 ec2-user ec2-user         32 abr 24 17:05 bin -> /mnt/disk/utils/hdf5-1.12.0/bin/
-rw-rw-r-- 1 ec2-user ec2-user 3032719802 abr 26 10:01 clean_alig_sort_heart10x.bam
-rw-r--r-- 1 ec2-user ec2-user 1392657081 abr 25 09:44 clean_unalig_heart10x.bam
-rw-rw-r-- 1 ec2-user ec2-user 9104699390 abr 24 15:26 clean_unalig_heart10x.fastq
-rw-rw-r-- 1 ec2-user ec2-user 1543182072 abr 26 11:28 gene_exon_tagged.bam
lrwxrwxrwx 1 ec2-user ec2-user         35 abr 24 17:05 libtool -> /mnt/disk/utils/hdf5-1.12.0/libtool
-rw-rw-r-- 1 ec2-user ec2-user 1511997713 abr 26 11:15 merged_align_heart10x.bam
drwxrwxr-x 2 ec2-user ec2-user       4096 abr 26 11:01 metadata
drwxrwxr-x 2 ec2-user ec2-user       4096 abr 24 15:22 mid_cleaned_bams
-rw-rw-r-- 1 ec2-user ec2-user 2328359756 abr 24 11:57 unalg_samptag_unpair_filt_trim.bam

```

**Comment by jamesnemesh** [comment]
You’ll want to fix this error (I should move that error to happen before the BAM sorting happens so you fail faster.)
Pick one of these options:
MIN_NUM_READS_PER_CELL=IntegerGather up all cell barcodes that have more than some number of reads.  Default value:
                              null. 

MIN_NUM_GENES_PER_CELL=IntegerThe minumum number of genes for a cell barcode to be reported.  Default value: null. 

MIN_NUM_TRANSCRIPTS_PER_CELL=Integer
                              The minumum number of transcripts for a cell barcode to be reported.  Default value: null.

NUM_CORE_BARCODES=Integer     Number of cells that you think are in the library.  This accomplishes the same goals as
                              the MIN_NUM_READS_CORE argument, but instead of defining barcodes as important based on
                              the number of reads, it picks the top  barcodes as core.  Default value: null. 

CELL_BC_FILE=File             Override CELL_BARCODE and MIN_NUM_READS_PER_CELL, and process reads that have the cell
                              barcodes in this file instead.  The file has 1 column with no header.  Default value:
                              null. 
-Jim

**Comment by MartaBenegas** [comment]
I've already added the MIN_NUM_GENES_PER_CELL=500 option. I've performed the BAMTagHistogram to take a look into my data and it generates an empty file with just the header. I'll redo the entire pipeline. 

Another thing: I'm using a 10x Chromium dataset ([this one](https://support.10xgenomics.com/single-cell-gene-expression/datasets/3.0.0/heart_1k_v2)) which has three fastq: one for read 1 (with cell barcode + UMI), one for read 2 (with transcripts) and another which contain sample indexes. So, if we don't take into account the sample index, reads from different samples could be grouped on the same cell barcode. Is there any way to take it into account with Drop-seq tools?

**Comment by jamesnemesh** [comment]
Hi,

You need to demultiplex your data into unmapped BAM files, 1 per sample.  Take a look at:

https://broadinstitute.github.io/picard/command-line-overview.html#ExtractIlluminaBarcodes <https://broadinstitute.github.io/picard/command-line-overview.html#ExtractIlluminaBarcodes>
https://broadinstitute.github.io/picard/command-line-overview.html#IlluminaBasecallsToSam <https://broadinstitute.github.io/picard/command-line-overview.html#IlluminaBasecallsToSam>

This is outside the typical dropseq workflow, so you may want to move over to Picard for more guidance for these tools.

Note that the lengths of the cell and molecular barcodes is different in 10x data compared to standard dropseq, so you’ll need to account for that.  Also, there are multiple versions of the 10x reagents which also have different cell and molecular barcode lengths, so you need to know which version of the reagents were used.

-Jim
