### ISSUE TITLE
Genes and strands must be of the same length

### ISSUE THREAD

**Issue by HYJ-hh** [broadinstitute/Drop-seq#340]
hello,
   I met the bug: 
  Exception in thread "main" java.lang.IllegalArgumentException: Genes and strands must be of the same length.
	at org.broadinstitute.dropseqrna.annotation.FunctionalDataProcessor.convert(FunctionalDataProcessor.java:45)
	at org.broadinstitute.dropseqrna.annotation.FunctionalDataProcessor.getFilteredFunctionalData(FunctionalDataProcessor.java:68)
	at org.broadinstitute.dropseqrna.utils.readiterators.GeneFunctionProcessor.getReadFunctions(GeneFunctionProcessor.java:105)
	at org.broadinstitute.dropseqrna.utils.readiterators.GeneFunctionProcessor.processRead(GeneFunctionProcessor.java:57)
	at org.broadinstitute.dropseqrna.utils.readiterators.GeneFunctionIteratorWrapper.processRecord(GeneFunctionIteratorWrapper.java:30)
	at org.broadinstitute.dropseqrna.utils.readiterators.GeneFunctionIteratorWrapper.processRecord(GeneFunctionIteratorWrapper.java:12)
	at org.broadinstitute.dropseqrna.utils.CountChangingIteratorWrapper.populateOutputQueue(CountChangingIteratorWrapper.java:56)
	at org.broadinstitute.dropseqrna.utils.CountChangingIteratorWrapper.hasNext(CountChangingIteratorWrapper.java:71)
	at org.broadinstitute.dropseqrna.utils.SortingIteratorFactory.create(SortingIteratorFactory.java:63)
	at org.broadinstitute.dropseqrna.utils.readiterators.SamRecordSortingIteratorFactory.create(SamRecordSortingIteratorFactory.java:57)
	at org.broadinstitute.dropseqrna.utils.readiterators.UMIIterator.<init>(UMIIterator.java:145)
	at org.broadinstitute.dropseqrna.utils.editdistance.DetectBeadSubstitutionErrors.doWork(DetectBeadSubstitutionErrors.java:147)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:308)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
	at org.broadinstitute.dropseqrna.cmdline.DropSeqMain.main(DropSeqMain.java:42)

But I couldn't find a solution to this problem

**Comment by jamesnemesh** [comment]
Hi,

This sounds like DetectBeadSubstitutionErrors had trouble parsing TagReadWithGeneFunction’s output.  The gene annotations for each read are encoded as a triplet as noted in the docs 

"This program provides 3 tags for each read, gn [gene name], gs [gene strand] and gf [gene function]. These tags can have more than one value, and the values are comma separated."

The expectation is that you have the same number of tags for each value, and the program is complaining that a read has a different number of gn and gs values.

There’s not much to go on in your message to help debug this further.

To help you further, I would need a minimum input set that reproduces this error - perhaps this occurs early in parsing the BAM file and you can isolate some reads that cause this error, then send me that smaller BAM file?  The rest of the program’s log isn’t attached, so I have no idea if this occurs early or late in the process.  I would also need the full command line you executed, and any other files you passed into the program.

-Jim
