### ISSUE TITLE
Read missing umi tag errors in 3.0.1

### ISSUE THREAD

**Issue by drneavin** [broadinstitute/Drop-seq#424]
Hello,

In my testing of Drop-seq v3.0.1 for Dropulation, I ran across the following error when the bam file doesn't have a UMI tag for the command `AssignCellsToSamples`:

```
Exception in thread "main" java.lang.IllegalArgumentException: Read A00488:13:H7LJTDSXX:4:1563:1027:32643       16      1       1402183 255     1S74M3552N23M      *       0       0       NGCCAAAGATTTGAAAGTCTTTGGCTCGTAGATGGCCAGATCCGCTAGGACTTTCCTGTTGAGCTCCACCTGGCACTTAACTAAATTCCCAATGAGCG      #,F,:FF,F::FFFFF:,F,::FFF,FF:FFFFFFFF:FF:FFFF::,FFF,F:FF,::,FFFFFFFFFFF:FFFFFFFFF,FFFFFFFFFF:FFFFF CB:Z:AGTGTCACATGCCTTC-1 BC:Z:CAATGGAG   RE:A:E  XF:Z:CODING     RG:Z:OneK1K_scRNA_Sample54_V2:MissingLibrary:1:H7LJTDSXX:4 NH:i:1  HI:i:1  nM:i:0  GN:Z:MRPL20     CR:Z:AGTGTCACATGCCTTC   UR:Z:CATCCGTTAN AS:i:96 QT:Z:FFFFFFFF   GX:Z:ENSG00000242485       TX:Z:ENST00000344843,+349,97M1S;ENST00000487659,+1326,97M1S;ENST00000493287,+137,97M1S  CY:Z:FFFFFFFFFFF:FFFF   UY:Z:FFF:FFFFF# gf:Z:CODING        gn:Z:MRPL20     gs:Z:-
 does not have a UMI tag UB
        at org.broadinstitute.dropseqrna.utils.readiterators.STARSoloChimericReadFilteringIterator.filterOut(STARSoloChimericReadFilteringIterator.java:48)
        at org.broadinstitute.dropseqrna.utils.readiterators.STARSoloChimericReadFilteringIterator.filterOut(STARSoloChimericReadFilteringIterator.java:34)
        at org.broadinstitute.dropseqrna.utils.FilteredIterator.skipUndesired(FilteredIterator.java:77)
        at org.broadinstitute.dropseqrna.utils.FilteredIterator.next(FilteredIterator.java:117)
        at htsjdk.samtools.util.PeekableIterator.advance(PeekableIterator.java:71)
        at htsjdk.samtools.util.PeekableIterator.next(PeekableIterator.java:57)
        at org.broadinstitute.dropseqrna.utils.FilteredIterator.next(FilteredIterator.java:116)
        at htsjdk.samtools.util.PeekableIterator.advance(PeekableIterator.java:71)
        at htsjdk.samtools.util.PeekableIterator.next(PeekableIterator.java:57)
        at org.broadinstitute.dropseqrna.utils.FilteredIterator.next(FilteredIterator.java:116)
        at htsjdk.samtools.util.PeekableIterator.advance(PeekableIterator.java:71)
        at htsjdk.samtools.util.PeekableIterator.next(PeekableIterator.java:57)
        at org.broadinstitute.dropseqrna.utils.FilteredIterator.next(FilteredIterator.java:116)
        at org.broadinstitute.dropseqrna.utils.CountChangingIteratorWrapper.populateOutputQueue(CountChangingIteratorWrapper.java:56)
        at org.broadinstitute.dropseqrna.utils.CountChangingIteratorWrapper.hasNext(CountChangingIteratorWrapper.java:71)
        at org.broadinstitute.dropseqrna.utils.SortingIteratorFactory.create(SortingIteratorFactory.java:63)
        at org.broadinstitute.dropseqrna.utils.readiterators.SamRecordSortingIteratorFactory.create(SamRecordSortingIteratorFactory.java:57)
        at org.broadinstitute.dropseqrna.barnyard.digitalallelecounts.SNPUMIBasePileupIterator.<init>(SNPUMIBasePileupIterator.java:136)
        at org.broadinstitute.dropseqrna.barnyard.digitalallelecounts.sampleassignment.AssignCellsToSamples.prepareIterator(AssignCellsToSamples.java:916)
        at org.broadinstitute.dropseqrna.barnyard.digitalallelecounts.sampleassignment.AssignCellsToSamples.doWork(AssignCellsToSamples.java:270)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:292)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:105)
        at org.broadinstitute.dropseqrna.cmdline.DropSeqMain.main(DropSeqMain.java:42)
```

Here's the command that I used:
```
AssignCellsToSamples \
            INPUT_BAM=$DROPULATION_OUTDIR/possorted_genome_bam_dropulation_tag.bam \
            OUTPUT="$DROPULATION_OUTDIR"/assignments.tsv.gz \
            VCF=$DROPULATION_OUTDIR/invcf.gz \
            SAMPLE_FILE="$INDS" \
            CELL_BARCODE_TAG='CB' \
            MOLECULAR_BARCODE_TAG='UB' \
            VCF_OUTPUT="$DROPULATION_OUTDIR"/assignment.vcf \
            MAX_ERROR_RATE=0.05 \
            CELL_BC_FILE="$BARCODES" \
            TMP_DIR="$DROPULATION_OUTDIR"
```

This is new behaviour that has changed since v2.5.4 (I tested with the same files, just changed the Drop-seq version) where I think it just ignores those reads and moves on. Is there anything that changed between v2.5.4 and v3.0.1 that could have led to this behaviour change and is there a way to revert back to a method where it ignores those reads?

Thanks for the help!

-Drew

**Comment by alecw** [comment]
Hi Drew,

Fixed by #425 .  Do you need a new release or can you just use master?  I wouldn't bother with a release in general because it's a little tedious, but if you need it I can do it.

Regards, Alec

**Comment by mschilli87** [comment]
@alecw: Personally I find versioned releases more citable than commit hashes in method sections but if @drneavin bundles current master in a versioned release of Demuxafy, I'll just use that one for my citations. 😉

**Comment by drneavin** [comment]
Thanks @alecw! 

I've only ever used the zip files provided in the releases. I think I would prefer the release but I can give building it myself a go. From the readme it looks simple enough:

1. `git clone https://github.com/broadinstitute/Drop-seq.git` and `cd Drop-seq`
2. `./gradlew distZip`
3. `unzip ./dropseq/build/distributions/dropseq-master.zip`

Let me know if you would change anything in those steps. I may ask for a release if I run into too much trouble trying to build it.

**Comment by drneavin** [comment]
Success! I was able to install this version of drop-seq and have tested it. It works well now, thanks!
