### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space when using DigitalExpression

### ISSUE THREAD

**Issue by fbrundu** [broadinstitute/Drop-seq#52]
I am using the latest version of Drop-seq_tools (2.0.0).

I am running DigitalExpression on a large bam (~300G) with the following call:

    DigitalExpression I=final.bam O=/dev/null SUMMARY=final.summary.txt \
        CELL_BC_FILE=barcodes.whitelist.txt EDIT_DISTANCE=1 \
        LOCUS_FUNCTION_LIST=INTRONIC TMP_DIR=./tmp

My objective is to get a count distribution for each barcode, using CODING+UTR+INTRONIC reads. After about 2.641G reads DigitalExpression ends with the following error:

```shell
java.lang.OutOfMemoryError: Java heap space
Dumping heap to java_pid97445.hprof ...
Heap dump file created [4420300120 bytes in 19.108 secs]
[Mon Oct 29 09:28:59 UTC 2018] org.broadinstitute.dropseqrna.barnyard.DigitalExpression done. Elapsed time: 702.25 minutes.
Runtime.totalMemory()=3593469952
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at htsjdk.samtools.BAMRecordCodec.decode(BAMRecordCodec.java:267)
        at htsjdk.samtools.BAMRecordCodec.decode(BAMRecordCodec.java:40)
        at htsjdk.samtools.util.SortingCollection$FileRecordIterator.advance(SortingCollection.java:626)
        at htsjdk.samtools.util.SortingCollection$FileRecordIterator.next(SortingCollection.java:616)
        at htsjdk.samtools.util.PeekIterator.peek(PeekIterator.java:69)
        at htsjdk.samtools.util.SortingCollection$PeekFileRecordIteratorComparator.compare(SortingCollection.java:653)
        at htsjdk.samtools.util.SortingCollection$PeekFileRecordIteratorComparator.compare(SortingCollection.java:648)
        at java.base/java.util.TreeMap.put(TreeMap.java:550)
        at java.base/java.util.TreeSet.add(TreeSet.java:255)
        at htsjdk.samtools.util.SortingCollection$MergingIterator.next(SortingCollection.java:562)
        at htsjdk.samtools.util.PeekableIterator.advance(PeekableIterator.java:71)
        at htsjdk.samtools.util.PeekableIterator.next(PeekableIterator.java:57)
        at org.broadinstitute.dropseqrna.utils.GroupingIterator.next(GroupingIterator.java:63)
        at org.broadinstitute.dropseqrna.utils.readiterators.UMIIterator.next(UMIIterator.java:151)
        at org.broadinstitute.dropseqrna.barnyard.DigitalExpression.digitalExpression(DigitalExpression.java:202)
        at org.broadinstitute.dropseqrna.barnyard.DigitalExpression.doWork(DigitalExpression.java:154)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:295)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
        at org.broadinstitute.dropseqrna.cmdline.DropSeqMain.main(DropSeqMain.java:42)
```

How to define maximum heap space through DigitalExpression?

Thanks,
Francesco

**Comment by alecw** [comment]
Hi Francesco,

Run 'DigitalExpression -h' for usage information, including setting the heap size.

Regards, Alec

**Comment by fbrundu** [comment]
Ah thanks!
I used to run DigitalExpression without `-h` to see its options. Now it's clear.

**Comment by vagabond12** [comment]
Though I saw the DigitalExpression options, but I still do not know how to solve it. Could you please help me? Thank you.
