### ISSUE TITLE
Error running CovertToRefFlat program (Danio rerio)

### ISSUE THREAD

**Issue by Jayesh-Kumar-Sundaram** [broadinstitute/Drop-seq#54]
Hi,

Subject: I tried converting the GTF file for Danio rerio from Ensemble 94 release and I got the error messages

Genome assembly used for dict file creation: ftp://ftp.ensembl.org/pub/release-94/fasta/danio_rerio/dna/Danio_rerio.GRCz11.dna.primary_assembly.fa.gz

GTF file used for creating reFlat file creation: ftp://ftp.ensembl.org/pub/release-94/gtf/danio_rerio/Danio_rerio.GRCz11.94.gtf.gz

When I tried converting the GTF file to refFlat file,

It showed the following error:
Exception in thread "main" java.lang.NullPointerException
	at org.broadinstitute.dropseqrna.annotation.GTFRecord.validate(GTFRecord.java:156)
	at org.broadinstitute.dropseqrna.annotation.GTFParser.next(GTFParser.java:90)
	at org.broadinstitute.dropseqrna.annotation.GTFParser.next(GTFParser.java:39)
	at htsjdk.samtools.util.PeekableIterator.advance(PeekableIterator.java:71)
	at htsjdk.samtools.util.PeekableIterator.next(PeekableIterator.java:57)
	at org.broadinstitute.dropseqrna.utils.FilteredIterator.next(FilteredIterator.java:71)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.broadinstitute.dropseqrna.annotation.GeneFromGTFBuilder.gatherByGeneName(GeneFromGTFBuilder.java:205)
	at org.broadinstitute.dropseqrna.annotation.GeneFromGTFBuilder.<init>(GeneFromGTFBuilder.java:48)
	at org.broadinstitute.dropseqrna.annotation.GTFReader.load(GTFReader.java:75)
	at org.broadinstitute.dropseqrna.annotation.GTFReader.load(GTFReader.java:70)
	at org.broadinstitute.dropseqrna.annotation.GeneAnnotationReader.loadGTFFile(GeneAnnotationReader.java:67)
	at org.broadinstitute.dropseqrna.annotation.GeneAnnotationReader.loadAnnotationsFile(GeneAnnotationReader.java:51)
	at org.broadinstitute.dropseqrna.annotation.GeneAnnotationReader.loadAnnotationsFile(GeneAnnotationReader.java:61)
	at org.broadinstitute.dropseqrna.annotation.ConvertToRefFlat.doWork(ConvertToRefFlat.java:71)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:295)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
	at org.broadinstitute.dropseqrna.cmdline.DropSeqMain.main(DropSeqMain.java:42)

But when I used the Human genome and annotation file from Ensemble 94 release, it worked!

Human genome: ftp://ftp.ensembl.org/pub/release-94/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz

Human GTF file used: ftp://ftp.ensembl.org/pub/release-94/gtf/homo_sapiens/Homo_sapiens.GRCh38.94.gtf.gz

Can you please tell me where I might be going wrong?

Thanks 

Jayesh

**Comment by Jayesh-Kumar-Sundaram** [comment]
Yeah. I found the nature of the problem!

Danio GTF file had some non-gene lines which didn't have "gene_name" and "transcript_name".

It is working fine now.

Jayesh
