### ISSUE TITLE
Error: TagBamWithReadSequenceExtended

### ISSUE THREAD

**Issue by Jayesh-Kumar-Sundaram** [broadinstitute/Drop-seq#57]
I got the following error while using the "TagBamWithReadSequenceExtended" program:

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 9
	at org.broadinstitute.dropseqrna.utils.BaseQualityFilter.scoreBaseQuality(BaseQualityFilter.java:41)
	at org.broadinstitute.dropseqrna.utils.TagBamWithReadSequenceExtended.processSingleRead(TagBamWithReadSequenceExtended.java:160)
	at org.broadinstitute.dropseqrna.utils.TagBamWithReadSequenceExtended.doWork(TagBamWithReadSequenceExtended.java:129)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:295)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
	at org.broadinstitute.dropseqrna.cmdline.DropSeqMain.main(DropSeqMain.java:42)

Where am I going wrong?

Jayesh

**Comment by jamesnemesh** [comment]
Can you show us your command line call?

That said, my guess would be your read length is shorter than the number of bases you’re asking to use as a tag.  This definitely could use a better error to make that clear.

-Jim

**Comment by Jayesh-Kumar-Sundaram** [comment]
[error_message.txt](https://github.com/broadinstitute/Drop-seq/files/2568871/error_message.txt)

I have attached the command line call along with the error message.

Thanks

Jayesh

**Comment by jamesnemesh** [comment]
I’ve checked in a small fix for this - it should at least give you a human readable error now to help you figure out what’s going on with your data.

-Jim
